import type { ThemeRecord } from './format';

export const DEFAULT_THEME_ID = 'default';

export const DEFAULT_THEME_PREVIEW = '/skin-default.png';

export const DEFAULT_THEME: ThemeRecord = {
    name: 'default',
    description: 'Brand New Story',
    version: '2.0',
    createdAt: '2025-03-26T04:42:22.128Z',
    tokens: [
        { name: '--bg-color-1', value: '#fff' },
        { name: '--bg-color-2', value: '#f2f4f5' },
        { name: '--bg-color-3', value: '#f8f9fb' },
        { name: '--blurred-bg-color', value: 'transparent' },
        { name: '--border-color-1', value: '#dfe2e6' },
        { name: '--border-color-2', value: '#e2e7ea' },
        { name: '--text-color-1', value: '#000' },
        { name: '--text-color-2', value: '#6f706f' },
        { name: '--text-color-3', value: '#6f706f' },
        { name: '--link-color', value: 'var(--primary-color)' },
        { name: '--deck-border-color', value: 'var(--border-color-2)' },
        { name: '--nav-content-border-width', value: '1px' },
        { name: '--nav-content-border-color', value: 'transparent' },
        { name: '--deck-heading-icon-color', value: 'var(--primary-color)' },
        { name: '--bar-primary-icon-color', value: 'var(--primary-color)' },
        { name: '--bar-secondary-icon-color', value: 'var(--text-color-1)' },
        { name: '--nav-secondary-icon-color', value: 'var(--text-color-1)' },
        { name: '--bar-bottom-icon-color', value: 'var(--text-color-1)' },
        { name: '--nav-primary-icon-color', value: 'var(--primary-color)' },
        { name: '--menu-bg-color', value: 'var(--bg-color-3)' },
        { name: '--text-color-primary-colored', value: 'var(--primary-color)' },
        { name: '--success-color', value: '#a3be8c' },
        { name: '--danger-color', value: '#e62552' },
        { name: '--follow-color', value: '#d8dee9' },
        { name: '--decks-gap', value: '0' },
        { name: '--deck-border-radius', value: '0' },
        { name: '--decks-padding', value: '0' },
        { name: '--decks-margin', value: '0px' },
        { name: '--deck-divider-width', value: '404px' },
        { name: '--side-padding-right', value: '0' },
        { name: '--nav-content-border-radius', value: '8px 0 0 8px' },
        { name: '--deck-border-width', value: '0' },
        { name: '--nav-content-bg-color', value: 'hsla(0,0%,100%,.5)' },
        { name: '--publish-textarea-bg-color', value: 'var(--bg-color-1)' },
        { name: '--deck-border-right', value: '1px solid var(--border-color-2)' },
        { name: '--decks-flex', value: '1' },
        { name: '--decks-border-radius', value: '8px 8px 0 0' },
        { name: '--decks-bg-color', value: 'hsla(0,0%,100%,.5)' },
        { name: '--scroll-bar-color', value: 'var(--border-color-1)' },
        { name: '--timeline-reaction-icon-color', value: '#dadadb' },
        { name: '--timeline-reaction-liked-icon-color', value: '#ea679b' },
        { name: '--timeline-reaction-reposted-icon-color', value: '#64c591' },
        { name: '--side-nav-hover-bg-color', value: 'hsla(0,0%,100%,.5)' },
        { name: '--publish-border', value: '1px solid var(--border-color-2)' },
        { name: '--publish-tool-button-color', value: '#6f706f' },
        { name: '--decks-border-left', value: '1px solid var(--border-color-2)' },
        { name: '--timeline-embed-border', value: '1px solid var(--border-color-2)' },
        { name: '--decks-height', value: 'calc(100dvh - var(--decks-margin, 0px))' },
        { name: '--decks-border', value: '1px solid var(--border-color-2)' },
        { name: '--decks-border-bottom', value: 'none' },
        { name: '--decks-box-shadow', value: '0 2px 8px #0000000a' },
        { name: '--decks-margin-bottom', value: '0' },
    ],
    variants: [
        {
            key: 'defaut-1',
            name: 'lightpink',
            swatch: '#f182ac',
            tokens: [
                { name: '--current-theme-color', value: '#f182ac' },
                { name: '--primary-color', value: 'var(--current-theme-color)' },
                { name: '--base-bg-color', value: '#f6e9ef' },
                { name: '--base-dark-bg-color', value: '#321a24' },
            ],
        },
        {
            key: 'defaut-2',
            name: 'pastelyellow',
            swatch: '#bfae20',
            tokens: [
                { name: '--current-theme-color', value: '#bfae20' },
                { name: '--primary-color', value: 'var(--current-theme-color)' },
                { name: '--base-bg-color', value: '#efead8' },
                { name: '--base-dark-bg-color', value: '#201d08' },
            ],
        },
        {
            key: 'defaut-3',
            name: 'lightblue',
            swatch: '#27c7cc',
            tokens: [
                { name: '--current-theme-color', value: '#27c7cc' },
                { name: '--primary-color', value: 'var(--current-theme-color)' },
                { name: '--base-bg-color', value: '#e0f1f1' },
                { name: '--base-dark-bg-color', value: '#082425' },
            ],
        },
        {
            key: 'defaut-4',
            name: 'royalblue',
            swatch: '#4c81fb',
            tokens: [
                { name: '--current-theme-color', value: '#4c81fb' },
                { name: '--primary-color', value: 'var(--current-theme-color)' },
                { name: '--base-bg-color', value: '#e0e5ef' },
                { name: '--base-dark-bg-color', value: '#0e1a33' },
            ],
        },
        {
            key: 'defaut-5',
            name: 'superorange',
            swatch: '#ed7331',
            tokens: [
                { name: '--current-theme-color', value: '#ed7331' },
                { name: '--primary-color', value: 'var(--current-theme-color)' },
                { name: '--base-bg-color', value: '#f4e9e1' },
                { name: '--base-dark-bg-color', value: '#2b1207' },
            ],
        },
        {
            key: 'defaut-6',
            name: 'violet',
            swatch: '#7a35f1',
            tokens: [
                { name: '--current-theme-color', value: '#7a35f1' },
                { name: '--primary-color', value: 'var(--current-theme-color)' },
                { name: '--base-bg-color', value: '#ece8f3' },
                { name: '--base-dark-bg-color', value: '#1f152e' },
            ],
        },
        {
            key: 'defaut-7',
            name: 'scarlet',
            swatch: '#f13551',
            tokens: [
                { name: '--current-theme-color', value: '#f13551' },
                { name: '--primary-color', value: 'var(--current-theme-color)' },
                { name: '--base-bg-color', value: '#f3e6e8' },
                { name: '--base-dark-bg-color', value: '#300a12' },
            ],
        },
        {
            key: 'defaut-8',
            name: 'lightgreen',
            swatch: '#8bb556',
            tokens: [
                { name: '--current-theme-color', value: '#8bb556' },
                { name: '--primary-color', value: 'var(--current-theme-color)' },
                { name: '--base-bg-color', value: '#e2e8db' },
                { name: '--base-dark-bg-color', value: '#19220f' },
            ],
        },
        {
            key: 'defaut-9',
            name: 'paperwhite',
            swatch: '#ffffff',
            tokens: [
                { name: '--current-theme-color', value: '#1b1b1b' },
                { name: '--primary-color', value: 'var(--current-theme-color)' },
                { name: '--base-bg-color', value: '#f3f3f3' },
                { name: '--base-dark-bg-color', value: '#100f0f' },
                { name: '--link-color', value: '#4c81fb' },
                { name: '--dark-primary-color', value: 'var(--text-color-2)' },
            ],
        },
        {
            key: 'defaut-10',
            name: 'jade',
            swatch: '#22bd77',
            tokens: [
                { name: '--current-theme-color', value: '#22bd77' },
                { name: '--primary-color', value: 'var(--current-theme-color)' },
                { name: '--base-bg-color', value: '#e6f4ed' },
                { name: '--base-dark-bg-color', value: '#082216' },
            ],
        },
        {
            key: 'defaut-11',
            name: 'platinumsilver',
            swatch: '#eeeeee',
            tokens: [
                { name: '--current-theme-color', value: '#45484e' },
                { name: '--primary-color', value: 'var(--current-theme-color)' },
                { name: '--base-bg-color', value: '#dbdde4' },
                { name: '--base-dark-bg-color', value: '#1b1c1e' },
                { name: '--link-color', value: '#4c81fb' },
                { name: '--dark-primary-color', value: 'var(--text-color-2)' },
            ],
        },
        {
            key: 'defaut-12',
            name: 'pinkgold',
            swatch: '#e3978c',
            tokens: [
                { name: '--current-theme-color', value: '#e3978c' },
                { name: '--primary-color', value: 'var(--current-theme-color)' },
                { name: '--base-bg-color', value: '#f1dfdd' },
                { name: '--base-dark-bg-color', value: '#30221d' },
            ],
        },
    ],
    dark: [
        { name: '--primary-color', value: 'var(--dark-primary-color,var(--current-theme-color))' },
        { name: '--app-bg-color', value: 'var(--base-dark-bg-color)' },
        { name: '--base-bg-color', value: '#1b1a19' },
        { name: '--bg-color-1', value: '#1d1e20' },
        { name: '--bg-color-2', value: '#272727' },
        { name: '--bg-color-3', value: '#1e1e1e' },
        { name: '--border-color-1', value: '#403d3d' },
        { name: '--border-color-2', value: '#3c3c3c' },
        { name: '--text-color-1', value: '#dee0e3' },
        { name: '--text-color-2', value: '#bababa' },
        { name: '--text-color-3', value: '#8f8f8f' },
        { name: '--timeline-embed-box-shadow', value: '0 0 0 1px var(--border-color-1) inset' },
        { name: '--timeline-embed-bg-color', value: 'var(--base-bg-color)' },
        { name: '--timeline-embed-border', value: 'none' },
        { name: '--decks-bg-color', value: 'rgba(0,0,0,.25)' },
        { name: '--nav-content-bg-color', value: 'rgba(0,0,0,.25)' },
        { name: '--side-nav-hover-bg-color', value: 'rgba(0,0,0,.25)' },
        { name: '--publish-textarea-bg-color', value: 'rgba(0,0,0,.25)' },
        { name: '--publish-tool-button-color', value: 'var(--text-color-1)' },
        { name: '--bubble-bg-color', value: 'rgba(0,0,0,.25)' },
        { name: '--notification-filter-bg-color', value: 'rgba(0,0,0,.25)' },
        { name: '--modal-page-bg-color', value: 'var(--bg-color-1)' },
        { name: '--timeline-reaction-icon-color', value: 'var(--border-color-1)' },
    ],
};

const OLD_COLOR_IDS = ['lightpink', 'pastelyellow', 'lightblue', 'royalblue', 'superorange', 'violet', 'scarlet', 'lightgreen', 'paperwhite', 'jade', 'platinumsilver', 'pinkgold'];

export function oldThemeConvert(currentTheme: string): string | null {
    const index = OLD_COLOR_IDS.indexOf(currentTheme);
    return index === -1 ? null : `defaut-${index + 1}`;
}
