// Generated by scripts/atmosphere-screenshots.mjs. Do not edit by hand.
export interface PresetScreenshot {
    src: string;
    width: number;
    height: number;
}

export const presetScreenshots: Record<string, PresetScreenshot[]> = {
    diary: [
        { src: '/atmosphere/diary/01.webp', width: 1600, height: 1000 },
    ],
    kaku: [
        { src: '/atmosphere/kaku/01.webp', width: 1600, height: 1000 },
    ],
    mochott: [
        { src: '/atmosphere/mochott/01.webp', width: 1600, height: 1000 },
    ],
    poll: [
        { src: '/atmosphere/poll/01.webp', width: 1600, height: 1000 },
    ],
    tomarigi: [
        { src: '/atmosphere/tomarigi/01.webp', width: 1600, height: 1000 },
    ],
};
